version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    networks:
      - cattlenetwork

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/dist:/app/dist
    networks:
      - cattlenetwork
      
networks:
  cattlenetwork:
    driver: bridge